labs13-quizzer/front-end

quizzer/package.json
quizzer/public/index.html
quizzer/src/App.js
quizzer/src/components/auth/Login.js
quizzer/yarn.lock

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added Oauth front-end

---

quizzer/src/components/QuizForm.js

-   [x] New feature (non-breaking change which adds functionality)
-   [x] Incomplete/work-in-progress, PR is for discussion/feedback
-   [ ] Test A
-   [ ] Test B
-   [ ] …

created component quizform

---

quizzer/src/components/Step2/Step2Page.js
quizzer/src/components/StripePage/CheckoutForm.js

Stripe checkout is working with Subscription, getting plan (ex ample, if customer choses "bronze", after checkout, it will show in the dashboad that customer is subscribed to bronze.
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [x] …

Rosa perez

---

quizzer/src/App.js

Fixes # (issue): resolved error in app.js route path, typo
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] Complete, but not tested (may need new tests)
-   [ ] Test A
-   [ ] Test B
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, …

resolved error in app.js route path, typo

---

quizzer/src/App.js

-   [x ] Bug fix (non-breaking change which fixes an issue)
-   [ x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [x ] I have performed a self-review of my own code
- …

changed development endpoint to production

---

quizzer/src/App.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

google auth

---

quizzer/src/App.js
quizzer/src/components/Login/Login.js
quizzer/src/components/Login/login.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Login Styles

---

quizzer/src/App.css
quizzer/src/components/QuizForm/SideBarNav.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added new button to sidebar nav

---

quizzer/src/App.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Login/Login.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

boilerplate

---

quizzer/src/components/QuizForm/AddQuiz.js
quizzer/src/components/QuizForm/QuizForm.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added add quiz function using hooks

---

quizzer/src/App.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Login/Login.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

student dashboard setup added

---

quizzer/src/App.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Login/Login.js
quizzer/src/components/student.js
quizzer/src/index.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added teacher dashboard barebones

---

quizzer/src/components/Dashboards/TeachersDashboard.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added teacher dashboard code

---

quizzer/src/components/QuizForm/AddQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

changed add quiz to class component

---

quizzer/src/App.css
quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/QuizForm.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added add question component

---

quizzer/src/components/Quiz/Quiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

scoretracker fixed

---

quizzer/src/components/Dashboards/TeachersDashboard.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

merge conflicts

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Login/Login.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added access code on front screen via button

---

quizzer/src/components/Dashboards/StudentsDashboard.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Marc thiongo

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Login/Login.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Joseph rios

---

quizzer/src/components/Login/Login.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

SLASH BE GONE

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/QuizForm/AddQuestion.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

made small changes

---

quizzer/src/components/QuizForm/AddQuestion.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

refactored quiz component

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/AddQuiz.js
quizzer/src/components/QuizForm/QuizForm.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

got creating quizzes to work somewhat

---

quizzer/src/App.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/studentDashboard.css
quizzer/src/components/Dashboards/teacherDashboard.css
quizzer/src/components/Login/Login.js
quizzer/src/components/Quiz/Quiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added all finished features needs styling

---

quizzer/package.json
quizzer/src/App.js
quizzer/src/components/Dashboards/Navigation/StudentNavigation.css
quizzer/src/components/Dashboards/Navigation/StudentNavigation.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/InfoComponents/accessCode.js
quizzer/src/index.js
quizzer/yarn.lock

-   [ ] Test A
-   [ ] Test B
-   [ ] …

navigation menu is complete, without border radius

---

quizzer/src/components/Dashboards/StudentsDashboard.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added changed

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/teacherDashboard.css
quizzer/src/components/StripePage/stripe.css

Fixes # (issue) fixed the color text on a button to match rest 
-   [ ] Test A
-   [ ] Test B
-   [ ] I have commented my code, …

syling button to match UX continue 2work on Stripe

---

quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/InfoComponents/accessCode.js
quizzer/src/components/Login/Login.js
quizzer/src/components/Quiz/Quiz.js
quizzer/src/components/Quiz/getQuiz.js
quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/AddQuiz.js
quizzer/src/components/QuizForm/EditQuiz.js
quizzer/src/components/Step2/Step2Page.js
quizzer/src/components/StripePage/CheckoutForm.js
quizzer/src/components/student.js
quizzer/src/components/teacher.js
quizzer/src/components/user.js

Fixes # (issue) All endpoint have been set to env link
-   [ ] Test A
-   [ ] Test B
-   [ ] I have commented my code, …

Endpoints set to env link

---

quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

found issue for questions bug

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/teacherDashboard.css
quizzer/src/components/InfoComponents/Folders.js
quizzer/src/components/InfoComponents/folders.css
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

folder system 

---

quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Quiz/Quiz.js
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

completed quiz for students and started on edit questions

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/teacherDashboard.css
quizzer/src/components/QuizForm/EditQuiz.js
quizzer/src/components/QuizForm/addQuiz.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

edit questions feature complete

---

quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/Cards/quizCard.css
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/teacherDashboard.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

fixed all folders open bug

---

quizzer/public/index.html

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added fontawesome link

---

quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

delete quiz auto removes from teacherdashboard

---

quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

adding quizzes to folders work again

---

quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/InfoComponents/Folders.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added re render on folders

---

quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/InfoComponents/FolderContents.js
quizzer/src/components/InfoComponents/Folders.js
quizzer/src/components/InfoComponents/QuizContents.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

updated folders and student dashboard

---

quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/InfoComponents/Folders.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

some UI fixes

---

quizzer/src/components/InfoComponents/QuizContents.js
quizzer/src/components/InfoComponents/accessCode.js
quizzer/src/components/QuizForm/EditQuestion.js
quizzer/src/components/QuizForm/EditQuiz.css
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

reformatted edit quiz and made folder links useable

---

quizzer/src/components/Cards/quizCard.css
quizzer/src/components/QuizForm/AddQuiz.js
quizzer/src/index.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

changes for styling

---

quizzer/src/components/Cards/quizCard.css
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.css
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/InfoComponents/Folders.js
quizzer/src/components/QuizForm/EditQuestion.js
quizzer/src/components/QuizForm/EditQuiz.css
quizzer/src/components/QuizForm/EditQuiz.js
quizzer/src/components/QuizForm/addQuiz.css
quizzer/src/index.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added edit question styles

---

quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/addQuiz.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

style changes

---

quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/EditQuestion.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

style fixes

---

quizzer/package.json
quizzer/src/App.css
quizzer/src/components/Cards/quizCard.css
quizzer/src/components/Dashboards/Navigation/StudentNavigation.css
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.css
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/studentDashboard.css
quizzer/src/components/Dashboards/teacherDashboard.css
quizzer/src/components/InfoComponents/Folders.js
quizzer/src/index.css
quizzer/yarn.lock

-   [ ] Test A
-   [ ] Test B
-   [ ] …

styles for nav

---

quizzer/src/components/Dashboards/Navigation/TeacherNavigation.css
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Dashboards/studentDashboard.css
quizzer/src/components/Dashboards/teacherDashboard.css

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added styling

---

quizzer/src/components/Dashboards/Navigation/StudentNavigation.js
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.css
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.js
quizzer/src/components/Dashboards/StudentsDashboard.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Dashboards/studentDashboard.css
quizzer/src/components/InfoComponents/Folders.js
quizzer/src/components/Login/Login.js
quizzer/src/components/Quiz/QuizOld.js
quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/EditQuestion.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added some styling changes and student dashboard fixes

---

quizzer/src/Stripe/Step2/Step2Page.js
quizzer/src/Stripe/StripePage/CheckoutForm.js
quizzer/src/Stripe/StripePage/stripe.css
quizzer/src/components/Cards/QuizCards.js
quizzer/src/components/Dashboards/Navigation/TeacherNavigation.js
quizzer/src/components/Dashboards/TeachersDashboard.js
quizzer/src/components/Quiz/Quiz.js
quizzer/src/components/QuizForm/AddQuestion.js
quizzer/src/components/QuizForm/AddQuiz.js
quizzer/src/components/QuizForm/EditQuiz.css
quizzer/src/components/QuizForm/EditQuiz.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added styling and isPaid is feature
